# Generated by Django 5.2.11 on 2026-02-28 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=80, verbose_name='Марка')),
                ('model', models.CharField(max_length=120, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(default=2020, verbose_name='Год')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('mileage_km', models.PositiveIntegerField(default=0, verbose_name='Пробег (км)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='В наличии (шт)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новый авто')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('done', 'Завершен'), ('canceled', 'Отменен')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_moment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.car')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
            ],
        ),
    ]
